name: to_do_list
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  fluttertoast: ^8.2.2
  awesome_snackbar_content: ^0.1.3
  google_sign_in: ^6.1.5
  flip_card: ^0.7.0
  flutter_svg: ^2.0.9
  firebase_messaging: ^14.7.3
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  cached_network_image: ^3.3.0
  geolocator: ^10.1.0
  image_cropper: ^5.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    #    - assets/images/jpgs/
    - assets/images/pngs/
    - assets/images/svgs/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Medium.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 500
        - asset: assets/fonts/RobotoCondensed-ExtraBold.ttf
          weight: 700
